"""DealScan - per-county scraper registry."""
from __future__ import annotations
from typing import Any, Dict, List
from . import arcgis
from .base import probe, ProbeResult

_DEFAULT_FIELDS={"apn":"APN","address":"SITUS_ADDR","lot_size_acres":"LAND_ACRES","assessed_value":"LIMITED_VALUE","market_value":"FULL_CASH_VALUE","owner_name":"OWNER_NAME","owner_address":"OWNER_MAIL_ADDR","owner_state":"OWNER_MAIL_STATE","tax_amount":"TAX_AMT","tax_delinquent_years":"TAX_DELINQ_YEARS","year_acquired":"SALE_YEAR","zoning":"ZONING","land_use":"LAND_USE","has_improvements":"HAS_IMPROVEMENTS","legal_description":"LEGAL_DESC","latitude":"LATITUDE","longitude":"LONGITUDE","last_sale_price":"SALE_PRICE","last_sale_date":"SALE_DATE"}

COUNTY_SCRAPERS: Dict[str, Dict[str, Any]]={
"cochise_az":{"name":"Cochise County, AZ","arcgis_root":"https://gis-cochise.opendata.arcgis.com","services":[("Parcels","Parcels",["parcel","ownership"]),("Assessor","Assessor",["parcel","ownership"]),("Hosted","Hosted",["parcel","ownership"])],"fields":{"apn":"apn","address":"situs_address","lot_size_acres":"acres","market_value":"fcv","owner_name":"owner_name1","owner_address":"address1","owner_state":"state","land_use":"use_code","legal_description":"legal_text","longitude":"geo_x","latitude":"geo_y"},"defaults":{"county_state":"Arizona"},"where":"1=1","verified":True,"html_search_url":"https://parcelinquirytreasurer.cochise.az.gov/Main/ParcelSearch","delinquent_list_url":"https://www.cochise.az.gov/treasurer"},
"mohave_az":{"name":"Mohave County, AZ","arcgis_root":"https://az-mohave.opendata.arcgis.com","services":[("Parcels","Parcels",["parcel","ownership"]),("Hosted","Hosted",["parcel","ownership"])],"fields":{"apn":"TAXPIN","address":"SITE_ADDRESS","owner_name":"OWNER","owner_address":"MAILING_ADDRESS","owner_state":"STATE","market_value":"ASSESSED_FULL_CASH_VALUE"},"defaults":{"county_state":"Arizona"},"where":"1=1","verified":True,"html_search_url":"https://www.mohave.gov/departments/assessor/assessor-search/","delinquent_list_url":"https://www.mohave.gov/departments/information-technology/gis-maps/"},
"el_paso_tx":{"name":"El Paso County, TX","data_mode":"arcgis","arcgis_layer_url":"https://services2.arcgis.com/fKvlzLJczghwPYHS/ArcGIS/rest/services/ElPasoCADWebService/FeatureServer/0","arcgis_root":"https://services2.arcgis.com/fKvlzLJczghwPYHS/ArcGIS/rest/services/ElPasoCADWebService/FeatureServer/0","fields":{"apn":"prop_id_text","address":["situs_num","situs_street_prefx","situs_street","situs_street_sufix","situs_city","situs_state","situs_zip"],"lot_size_acres":"legal_acreage","market_value":"market","improvement_value":"imprv_val","legal_description":["legal_desc","legal_desc2","legal_desc3"],"owner_name":"file_as_name"},"defaults":{"county_state":"Texas","land_use":"VACANT"},"where":"legal_acreage > 0 AND imprv_val = 0","verified":True,"html_search_url":"https://www.epcad.org","status":"EPCAD direct ArcGIS FeatureServer; vacant-land query uses official improvement value"},
"yavapai_az":{"name":"Yavapai County, AZ","data_mode":"arcgis","arcgis_layer_url":"https://gis.yavapaiaz.gov/arcgis/rest/services/Property/FeatureServer/10","arcgis_root":"https://gis.yavapaiaz.gov/arcgis/rest/services/Property/FeatureServer/10","fields":{"apn":"PARCELNO","lot_size_acres":"ACRE_CALC","land_use":"LEGAL_CLASS","property_type":"ACCOUNT_TYPE","year_acquired":"BUILDDATEID"},"defaults":{"county_state":"Arizona","land_use":"VACANT"},"where":"1=1","verified":True,"enrichment":{"layer_url":"https://gis.yavapaiaz.gov/arcgis/rest/services/Property/FeatureServer/4","join_source":"PARCELNO","join_target":"PARCEL_ID","fields":{"address":"ADDRESS","owner_name":"NAME","owner_address":"CO_ADDRESS","zoning":"ZONING","lot_size_acres":"ACRE_DEED","legal_description":"PARLABEL"}},"html_search_url":"https://www.yavapaiaz.gov/Mapping-and-Properties/GIS-Mapping/GIS-Mapping-Applications","status":"Official Vacant Land layer plus parcel enrichment."},
"washoe_nv":{"name":"Washoe County, NV","data_mode":"arcgis","arcgis_layer_url":"https://gisenterprise.washoecounty.gov/server/rest/services/WashoeGIS/Parcels/FeatureServer/0","arcgis_root":"https://gisenterprise.washoecounty.gov/server/rest/services/WashoeGIS/Parcels/FeatureServer/0","fields":{"apn":"APN","address":["STREETNUM","STREET","CITY","SITUSZIP"],"owner_name":["FIRSTNAME","LASTNAME"],"owner_address":"MAILING1","owner_state":"MAILSTATE","lot_size_acres":"ACREAGE","assessed_value":"LANDASS","market_value":"TOTALASS","improvement_value":"BUILDASS","zoning":"Zoning","land_use":"LAND_USE","water":"WATER","sewer":"SEWER","last_sale_price":"SALEPRICE","last_sale_date":"SALEDATE"},"defaults":{"county_state":"Nevada"},"where":"ACREAGE > 0","verified":True,"html_search_url":"https://www.washoecounty.gov/assessor/"},
"pinal_az":{"name":"Pinal County, AZ","data_mode":"arcgis","arcgis_layer_url":"https://rogue.casagrandeaz.gov/arcgis/rest/services/Pinal_County/Pinal_County_Parcels/FeatureServer/0","arcgis_root":"https://rogue.casagrandeaz.gov/arcgis/rest/services/Pinal_County/Pinal_County_Parcels/FeatureServer/0","fields":{"apn":"PARCELID","address":"SITEADDRESS","owner_name":"OWNERNME1","owner_address":"PSTLADDRESS","owner_state":"PSTLSTATE","market_value":"LNDVALUE","assessed_value":"CNTASSDVAL","tax_amount":"TOTCNTTXOD","lot_size_acres":"GROSSAC","land_use":"USEDSCRP","property_type":"CLASSDSCRP","has_improvements":"BLDGAREA","improvement_value":"BLDGAREA","last_sale_price":"SALEPRICE","last_sale_date":"SALEDATE"},"defaults":{"county_state":"Arizona"},"where":"GROSSAC > 0 AND (BLDGAREA IS NULL OR BLDGAREA = 0)","verified":True,"html_search_url":"https://www.pinal.gov/assessor"},
"hudson_co":{"name":"Huerfano County, CO","data_mode":"arcgis","arcgis_layer_url":"https://gis.colorado.gov/public/rest/services/Address_and_Parcel/Colorado_Public_Parcels/FeatureServer/0","arcgis_root":"https://gis.colorado.gov/public/rest/services/Address_and_Parcel/Colorado_Public_Parcels/FeatureServer/0","fields":{"apn":"parcel_id","address":["situsAdd","sitAddCty","sitAddZip"],"lot_size_acres":"landAcres","owner_name":"owner","owner_address":"ownerAdd","owner_state":"ownAddStt","zoning":"zoningDesc","land_use":"landUseDsc","legal_description":"legalDesc","market_value":"apprValTot","assessed_value":"asedValTot","last_sale_price":"salePrice","last_sale_date":"saleDate"},"defaults":{"county_state":"Colorado"},"where":"countyFips = '08055' AND landAcres > 0","verified":True,"html_search_url":"https://huerfano.us/departments/assessor/","status":"Colorado statewide public parcel composite filtered to Huerfano FIPS 08055; county assessor remains authoritative for valuation/title verification."},
"socorro_nm":{"name":"Socorro County, NM","data_mode":"arcgis","arcgis_layer_url":"https://gis.ose.nm.gov/server_s/rest/services/Parcels/County_Parcels_2026/MapServer/28","arcgis_root":"https://gis.ose.nm.gov/server_s/rest/services/Parcels/County_Parcels_2026/MapServer/28","fields":{"apn":"AccountNumber","address":"SitusAddressAll","owner_name":"OwnerAll","owner_address":"MailAddressAll","owner_state":"MailState","lot_size_acres":"LandArea","land_use":"LandUseDescription","zoning":"ZoningDescription","legal_description":"LegalDescription","improvement_value":"StructureCount","last_sale_price":"salePrice","last_sale_date":"CamaCurrentTo"},"defaults":{"county_state":"New Mexico"},"where":"LandArea > 0","verified":True,"html_search_url":"https://socorrocountynm-assessor.tylerhost.net/assessor/taxweb/","status":"New Mexico state parcel composite, Socorro County layer 28; assessor data includes ownership, sales, tax and assessment history while parcel layer supplies land area/use/zoning/structure count."},
}

def probe_county(county_id:str)->List[ProbeResult]:
    cfg=COUNTY_SCRAPERS.get(county_id)
    if not cfg:return [ProbeResult(county_id,"registry","",False,0,"unknown county")]
    root=cfg.get("arcgis_root"); results=[]
    if root:
        if "opendata.arcgis.com" in root:
            layer=arcgis.find_layer_via_hub(root,["parcel","ownership"]); results.append(ProbeResult(county_id,"arcgis-hub-dcat",f"{root}/api/feed/dcat-us/1.1.json",bool(layer),200 if layer else 404,layer or "no parcel layer found in DCAT feed",verified=bool(layer),extras={"layer":layer or ""}))
        else:
            url=root+"?f=json"; results.append(probe(url,county_id,"arcgis-layer",expect="arcgis"))
    return results
