'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'

interface Deal {
  apn?: string
  address?: string
  county_id?: string
  lot_size_acres?: number
  asking_price?: number
  deal_score?: number
  estimated_arv_low?: number
  estimated_arv_high?: number
  estimated_profit_low?: number
  estimated_profit_high?: number
  recommended_offer_low?: number
  recommended_offer_high?: number
  market_velocity?: number
  competition_level?: string
  valuation_basis?: string
  valuation_confidence?: number
  source_url?: string
  verification_status?: string
}
interface DealsResponse { deals: Deal[]; generated_at?: string | null; count?: number; meta?: { status?: string; scraped_counties?: string[]; storage_source?: string } }

const money = (value?: number) => typeof value === 'number' ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value) : '—'
const titleCase = (value?: string) => value ? value.replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase()) : '—'

function ScoreRing({ score }: { score?: number }) {
  const value = typeof score === 'number' ? Math.max(0, Math.min(100, score)) : 0
  return <div className="relative grid h-16 w-16 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#176b45 ${value * 3.6}deg, #e7ece9 0deg)` }}><div className="grid h-12 w-12 place-items-center rounded-full bg-white"><span className="text-lg font-black text-[#153025]">{score ?? '—'}</span></div></div>
}

function Metric({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) {
  return <div className="rounded-2xl border border-[#e7ece9] bg-[#f8faf9] px-4 py-3"><p className="text-[11px] font-bold uppercase tracking-[0.14em] text-[#8a958f]">{label}</p><p className={`mt-1.5 text-lg font-black tracking-tight ${accent ? 'text-[#176b45]' : 'text-[#18251f]'}`}>{value}</p></div>
}

export default function DealsPage() {
  const [data, setData] = useState<DealsResponse>({ deals: [] }); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('')
  const [query, setQuery] = useState(''); const [county, setCounty] = useState('all'); const [minScore, setMinScore] = useState(0); const [sort, setSort] = useState<'score' | 'profit' | 'price'>('score')
  const loadDeals = useCallback(async (silent = false) => { silent ? setRefreshing(true) : setLoading(true); try { const res = await fetch('/api/deals?limit=50', { cache: 'no-store' }); if (!res.ok) throw new Error(); setData(await res.json() as DealsResponse); setError('') } catch { setError('The deal feed is temporarily unavailable. Showing the latest data already loaded.') } finally { setLoading(false); setRefreshing(false) } }, [])
  useEffect(() => { void loadDeals(); const timer = window.setInterval(() => void loadDeals(true), 60000); return () => window.clearInterval(timer) }, [loadDeals])
  const counties = useMemo(() => Array.from(new Set(data.deals.map(d => d.county_id).filter(Boolean))).sort() as string[], [data.deals])
  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return data.deals.filter(d => county === 'all' || d.county_id === county).filter(d => (d.deal_score ?? 0) >= minScore).filter(d => !needle || `${d.address ?? ''} ${d.apn ?? ''} ${d.county_id ?? ''}`.toLowerCase().includes(needle)).sort((a,b) => sort === 'profit' ? (b.estimated_profit_high ?? 0) - (a.estimated_profit_high ?? 0) : sort === 'price' ? (a.asking_price ?? Infinity) - (b.asking_price ?? Infinity) : (b.deal_score ?? 0) - (a.deal_score ?? 0)) }, [data.deals, county, minScore, query, sort])
  const isDemo = data.meta?.storage_source === 'seed' || data.meta?.status === 'demo'; const statusLabel = isDemo ? 'Demo data' : data.meta?.status === 'degraded' ? 'Feed degraded' : 'Verified feed'
  const avgScore = data.deals.length ? Math.round(data.deals.reduce((sum,d) => sum + (d.deal_score ?? 0),0) / data.deals.length) : 0
  const avgProfit = data.deals.length ? data.deals.reduce((sum,d) => sum + (d.estimated_profit_high ?? 0),0) / data.deals.length : 0

  return <main className="min-h-screen bg-[#f7f9f7] text-[#15211b]">
    <header className="sticky top-0 z-30 border-b border-[#e6ebe8]/90 bg-white/85 backdrop-blur-2xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><a href="/" className="text-[17px] font-black tracking-tight">Deal<span className="text-[#176b45]">Scan</span></a><div className="flex items-center gap-2"><button onClick={() => void loadDeals(true)} disabled={refreshing} className="rounded-xl border border-[#dfe6e2] bg-white px-3.5 py-2 text-sm font-bold text-[#34423b] transition hover:border-[#176b45]/30 hover:bg-[#f4f8f5] disabled:opacity-50">{refreshing ? 'Refreshing…' : 'Refresh'}</button><a href="/" className="hidden rounded-xl bg-[#153025] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#176b45] sm:inline-flex">Home</a></div></div></header>

    <section className="relative overflow-hidden border-b border-[#e5ebe7] bg-white"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(#176b4510_1px,transparent_1px),linear-gradient(90deg,#176b4510_1px,transparent_1px)] [background-size:48px_48px]"/><div className="relative mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16"><div className="max-w-4xl"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1.5 text-xs font-black uppercase tracking-[0.12em] ${isDemo ? 'bg-[#fff5df] text-[#9a6515]' : 'bg-[#e8f4ec] text-[#176b45]'}`}>{statusLabel}</span>{data.meta?.scraped_counties?.length ? <span className="text-xs font-bold text-[#7f8b85]">{data.meta.scraped_counties.length} source counties</span> : null}</div><h1 className="mt-5 max-w-3xl text-4xl font-black tracking-[-0.04em] sm:text-6xl">Find land deals worth a closer look.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#65726b] sm:text-lg">Discover opportunities, understand the economics, then verify the evidence before you act.</p></div>
      <div className="mt-9 rounded-[2rem] border border-[#dfe7e2] bg-white/90 p-2 shadow-[0_24px_80px_rgba(22,45,34,0.09)] backdrop-blur"><div className="flex flex-col gap-2 lg:flex-row"><label className="flex min-h-14 flex-1 items-center gap-3 rounded-2xl bg-[#f5f8f6] px-4 ring-1 ring-inset ring-[#e4ebe7] focus-within:ring-2 focus-within:ring-[#176b45]/30"><span className="text-[#718078]">⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search address, APN or county" aria-label="Search deals" className="w-full bg-transparent text-sm font-semibold outline-none placeholder:text-[#98a29d]"/><kbd className="hidden rounded-lg border border-[#dce4df] bg-white px-2 py-1 text-[10px] font-bold text-[#87928c] sm:block">⌘ K</kbd></label><select value={county} onChange={e => setCounty(e.target.value)} aria-label="Filter county" className="min-h-14 rounded-2xl border border-[#e4ebe7] bg-[#f5f8f6] px-4 text-sm font-bold text-[#46534c] outline-none focus:ring-2 focus:ring-[#176b45]/20"><option value="all">All counties</option>{counties.map(c => <option key={c} value={c}>{titleCase(c)}</option>)}</select><select value={String(minScore)} onChange={e => setMinScore(Number(e.target.value))} aria-label="Minimum score" className="min-h-14 rounded-2xl border border-[#e4ebe7] bg-[#f5f8f6] px-4 text-sm font-bold text-[#46534c] outline-none focus:ring-2 focus:ring-[#176b45]/20"><option value="0">Any score</option><option value="50">50+ score</option><option value="70">70+ score</option><option value="80">80+ score</option><option value="90">90+ score</option></select><select value={sort} onChange={e => setSort(e.target.value as typeof sort)} aria-label="Sort deals" className="min-h-14 rounded-2xl border border-[#e4ebe7] bg-[#f5f8f6] px-4 text-sm font-bold text-[#46534c] outline-none focus:ring-2 focus:ring-[#176b45]/20"><option value="score">Highest score</option><option value="profit">Highest profit</option><option value="price">Lowest price</option></select></div></div>
    </div></section>

    <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Published opportunities" value={String(data.count ?? data.deals.length)} /><Metric label="Average DealScore" value={loading ? '—' : `${avgScore}/100`} accent /><Metric label="Avg. upside signal" value={loading ? '—' : money(avgProfit)} accent /></div>{isDemo && <div className="mt-4 rounded-2xl border border-[#ead9b8] bg-[#fffaf0] px-4 py-3 text-sm font-medium text-[#76521b]">Seed records are clearly labeled. Treat them as interface/data-shape previews, not verified investment opportunities.</div>}{error && <div role="alert" className="mt-4 rounded-2xl border border-[#ead9b8] bg-[#fffaf0] px-4 py-3 text-sm font-medium text-[#76521b]">{error}</div>}
      <div className="mb-5 mt-10 flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#8b9690]">Opportunity feed</p><h2 className="mt-1 text-2xl font-black tracking-tight">{filtered.length} {filtered.length === 1 ? 'match' : 'matches'}</h2></div><span className="hidden text-xs font-semibold text-[#8b9690] sm:block">Scores are screening signals, not guarantees.</span></div>
      {loading ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="h-80 animate-pulse rounded-[1.75rem] border border-[#e7ece9] bg-white"/>)}</div> : filtered.length === 0 ? <div className="rounded-[1.75rem] border border-dashed border-[#cfd9d3] bg-white p-14 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#eef4f0] text-xl">⌕</div><h2 className="mt-5 text-xl font-black">No matching opportunities</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-[#718078]">Clear a filter or broaden the search. DealScan only presents records available from its current published feed.</p><button onClick={() => {setQuery('');setCounty('all');setMinScore(0)}} className="mt-5 rounded-xl bg-[#153025] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#176b45]">Clear filters</button></div> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((deal,index)=><article key={`${deal.apn}-${index}`} className="group relative overflow-hidden rounded-[1.75rem] border border-[#e3e9e5] bg-white p-5 shadow-[0_12px_45px_rgba(23,42,32,0.045)] transition duration-300 hover:-translate-y-1 hover:border-[#b9cfc1] hover:shadow-[0_24px_70px_rgba(23,42,32,0.10)] sm:p-6"><div className="absolute inset-x-0 top-0 h-1 bg-[#176b45] opacity-0 transition group-hover:opacity-100"/><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><span className="rounded-full bg-[#edf5f0] px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.12em] text-[#176b45]">{titleCase(deal.county_id)}</span>{deal.verification_status && <span className="text-[10px] font-bold text-[#87928c]">{titleCase(deal.verification_status)}</span>}</div><h3 className="mt-3 line-clamp-2 text-xl font-black tracking-tight">{deal.address || 'Parcel opportunity'}</h3><p className="mt-1 truncate font-mono text-[11px] text-[#929d97]">APN {deal.apn || '—'}</p></div><ScoreRing score={deal.deal_score}/></div>
        <div className="mt-6 grid grid-cols-2 gap-2.5"><Metric label="Ask" value={money(deal.asking_price)} /><Metric label="Profit signal" value={money(deal.estimated_profit_high)} accent /><Metric label="ARV" value={money(deal.estimated_arv_high)} /><Metric label="Lot" value={deal.lot_size_acres ? `${deal.lot_size_acres.toLocaleString()} ac` : '—'} /></div>
        <div className="mt-5 rounded-2xl bg-[#f7faf8] p-4"><div className="flex items-center justify-between gap-3"><span className="text-xs font-bold text-[#77837c]">Recommended offer</span><span className="text-sm font-black text-[#18251f]">{money(deal.recommended_offer_low)}–{money(deal.recommended_offer_high)}</span></div>{deal.valuation_confidence != null && <div className="mt-3"><div className="mb-1.5 flex justify-between text-[10px] font-bold uppercase tracking-wider text-[#8a958f]"><span>Valuation confidence</span><span>{Math.round(deal.valuation_confidence * 100)}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#e1e8e3]"><div className="h-full rounded-full bg-[#176b45]" style={{width:`${Math.max(0,Math.min(100,deal.valuation_confidence*100))}%`}}/></div></div>}</div>
        <div className="mt-5 flex items-center justify-between border-t border-[#edf0ee] pt-4"><span className="text-xs text-[#8b9690]">{deal.valuation_basis ? titleCase(deal.valuation_basis) : 'Published record'}</span><div className="flex items-center gap-3">{deal.source_url && <a href={deal.source_url} target="_blank" rel="noreferrer" className="text-xs font-bold text-[#176b45] hover:underline">Source ↗</a>}{deal.apn && <a href={`/deals/${encodeURIComponent(deal.apn)}`} className="rounded-xl bg-[#153025] px-3.5 py-2 text-xs font-bold text-white transition hover:bg-[#176b45]">Review deal →</a>}</div></div>
      </article>)}</div>}
      <div className="mt-8 flex flex-wrap justify-between gap-3 text-xs font-semibold text-[#8b9690]"><span>Showing {filtered.length} of {data.deals.length} published records</span>{data.generated_at && <span>Updated {new Date(data.generated_at).toLocaleString()}</span>}</div>
    </section>
  </main>
}
