const features = [
  { title:'Property evidence', description:'Keep a parcel tied to its county and original source. Unknown acreage, coordinates or vacancy facts are not replaced with estimates.', rows:[['Identity','County + parcel identifier'],['Provenance','Source record and ingestion audit'],['Vacancy','Positive evidence required']] },
  { title:'Comparable sales', description:'Valuation requires at least three distinct, traceable land sales. An assessment value is not an asking price or a comparable transaction.', rows:[['Location','Nearby and acreage-relevant'],['Timing','Recent and not future-dated'],['Land at sale','Vacancy and sale qualification documented']] },
  { title:'Transparent economics', description:'Public opportunities need a source-backed asking price and complete documented costs. Without those inputs, a parcel stays held privately.', rows:[['Asking price','Actual source input'],['ARV','Calculated from qualified sales'],['Profit estimate','ARV less asking price and costs']] },
  { title:'Human due diligence', description:'Screening does not establish clear title, buildability, physical access, utilities or flood safety. Investigate those questions independently.', rows:[['Title and access','Independent review'],['Zoning and utilities','Local verification'],['Purchase decision','Your judgment, not a guarantee']] },
]
export default function Solution() {
  return <section className="relative overflow-hidden border-y border-[#e1e8e3] bg-white px-6 py-24 md:px-8" id="capabilities">
    <div className="mx-auto max-w-6xl"><div className="mb-14 max-w-2xl" data-reveal><p className="mb-4 text-[11px] font-bold uppercase tracking-[.12em] text-[#176b45]">Evidence and limits</p><h2 className="text-3xl font-bold tracking-[-.025em] text-[#15211b] md:text-4xl">Research grounded in what is known.</h2><p className="mt-4 text-sm leading-7 text-[#64716a]">These are the checks behind the workflow, not populated property reports or claims of live national coverage.</p></div>
      <div className="grid gap-6 md:grid-cols-2">{features.map((feature,i)=><article key={feature.title} className="rounded-2xl border border-[#dfe7e2] bg-[#f8faf9] p-7" data-reveal><p className="text-xs font-bold text-[#176b45]">0{i+1}</p><h3 className="mt-3 text-xl font-bold text-[#26352d]">{feature.title}</h3><p className="mt-3 text-sm leading-7 text-[#64716a]">{feature.description}</p><dl className="mt-6 divide-y divide-[#dfe7e2]">{feature.rows.map(([label,value])=><div key={label} className="flex justify-between gap-5 py-3 text-xs leading-5"><dt className="text-[#7a867f]">{label}</dt><dd className="text-right font-semibold text-[#34423b]">{value}</dd></div>)}</dl></article>)}</div>
    </div>
  </section>
}
