-- DealScan production schema. Keep this migration in sync with the deployed Supabase project.
create table if not exists public.counties (
  county_id text primary key,
  state text,
  state_fips text,
  county_fips text,
  county_name text not null,
  coverage_status text,
  data_source_type text,
  gis_url text,
  parcel_source_url text,
  arcgis_layer_url text,
  source_vendor text,
  scraper_type text,
  field_mapping jsonb not null default '{}'::jsonb,
  verification_status text,
  validation_status text,
  data_freshness timestamptz,
  discovery_attempted_at timestamptz,
  last_successful_run timestamptz,
  last_run_status text,
  last_run_error text,
  record_count integer default 0,
  qualified_count integer default 0,
  published_count integer default 0,
  persisted_count integer default 0,
  notes text,
  extra jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  apn text not null,
  county_id text not null references public.counties(county_id),
  address text,
  lot_size_acres numeric,
  assessed_value numeric,
  market_value numeric,
  owner_name text,
  owner_address text,
  owner_state text,
  tax_amount numeric,
  tax_delinquent_years integer not null default 0,
  year_acquired integer,
  zoning text,
  land_use text,
  has_improvements boolean not null default false,
  legal_description text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(apn, county_id)
);

create table if not exists public.deals (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id),
  deal_score integer not null default 0,
  asking_price numeric,
  estimated_arv_low numeric,
  estimated_arv_high numeric,
  estimated_costs numeric,
  estimated_profit_low numeric,
  estimated_profit_high numeric,
  recommended_offer_low numeric,
  recommended_offer_high numeric,
  motivation_signals text,
  motivation_score numeric,
  market_velocity numeric,
  competition_level text,
  status text not null default 'discovered',
  notes text,
  source text,
  source_url text,
  source_vendor text,
  source_quality text,
  verification_status text,
  data_freshness text,
  valuation_basis text,
  valuation_confidence numeric,
  discovered_at timestamptz not null default now(),
  delivered_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.comps (
  id bigint generated by default as identity primary key,
  deal_id bigint not null references public.deals(id) on delete cascade,
  address text,
  sale_price numeric,
  sale_date timestamptz,
  distance_miles numeric,
  lot_size_acres numeric,
  price_per_acre numeric
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text,
  tier text not null default 'free',
  budget_min numeric not null default 5000,
  budget_max numeric not null default 50000,
  target_states text,
  target_counties text,
  min_profit numeric not null default 3000,
  joined_at timestamptz not null default now(),
  is_active boolean not null default true
);

create table if not exists public.deliveries (
  id bigint generated by default as identity primary key,
  subscriber_id bigint references public.subscribers(id),
  deal_id bigint references public.deals(id),
  delivered_at timestamptz not null default now()
);

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text,
  joined_at timestamptz not null default now()
);

create index if not exists idx_properties_county on public.properties(county_id);
create index if not exists idx_deals_status_score on public.deals(status, deal_score desc);
create index if not exists idx_deals_property on public.deals(property_id);
create index if not exists idx_comps_deal on public.comps(deal_id);

create or replace function public.set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists counties_set_updated_at on public.counties;
create trigger counties_set_updated_at before update on public.counties for each row execute function public.set_updated_at();
drop trigger if exists properties_set_updated_at on public.properties;
create trigger properties_set_updated_at before update on public.properties for each row execute function public.set_updated_at();
drop trigger if exists deals_set_updated_at on public.deals;
create trigger deals_set_updated_at before update on public.deals for each row execute function public.set_updated_at();

alter table public.counties enable row level security;
alter table public.properties enable row level security;
alter table public.deals enable row level security;
alter table public.comps enable row level security;
alter table public.subscribers enable row level security;
alter table public.deliveries enable row level security;
alter table public.waitlist enable row level security;
