-- Durable run/record audit and idempotent persistence. No seed data.
create table if not exists public.ingestion_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  county_id text not null references public.counties(county_id),
  run_type text not null default 'manual',
  status text not null default 'running' check (status in ('running','completed','partial','failed','skipped')),
  source_url text,
  started_at timestamptz not null default now(),
  heartbeat_at timestamptz not null default now(),
  finished_at timestamptz,
  records_seen integer not null default 0 check (records_seen >= 0),
  records_normalized integer not null default 0 check (records_normalized >= 0),
  records_persisted integer not null default 0 check (records_persisted >= 0),
  records_rejected integer not null default 0 check (records_rejected >= 0),
  records_held integer not null default 0 check (records_held >= 0),
  records_skipped integer not null default 0 check (records_skipped >= 0),
  deals_persisted integer not null default 0 check (deals_persisted >= 0),
  records_failed integer not null default 0 check (records_failed >= 0),
  records_published integer not null default 0 check (records_published >= 0),
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  unique(id, county_id),
  check ((status = 'running') = (finished_at is null))
);

-- Earlier deployments may already have audit tables. Upgrade missing fields
-- explicitly; CREATE TABLE IF NOT EXISTS by itself is not a schema migration.
-- Unsupported primary-key types fail visibly instead of discarding history.
do $$ begin
  if exists (select 1 from information_schema.columns where table_schema='public'
      and table_name in ('ingestion_runs','ingestion_records') and column_name='id'
      and udt_name not in ('int8','int4')) then
    raise exception 'Audit IDs must be integer/bigint; export and migrate the legacy audit schema before this migration';
  end if;
end $$;
alter table public.ingestion_runs add column if not exists run_key text;
alter table public.ingestion_runs add column if not exists county_id text;
alter table public.ingestion_runs add column if not exists run_type text not null default 'manual';
alter table public.ingestion_runs add column if not exists status text not null default 'running';
alter table public.ingestion_runs add column if not exists source_url text;
alter table public.ingestion_runs add column if not exists started_at timestamptz not null default now();
alter table public.ingestion_runs add column if not exists heartbeat_at timestamptz not null default now();
alter table public.ingestion_runs add column if not exists finished_at timestamptz;
alter table public.ingestion_runs add column if not exists records_seen integer not null default 0;
alter table public.ingestion_runs add column if not exists records_normalized integer not null default 0;
alter table public.ingestion_runs add column if not exists records_persisted integer not null default 0;
alter table public.ingestion_runs add column if not exists records_rejected integer not null default 0;
alter table public.ingestion_runs add column if not exists records_held integer not null default 0;
alter table public.ingestion_runs add column if not exists records_skipped integer not null default 0;
alter table public.ingestion_runs add column if not exists deals_persisted integer not null default 0;
alter table public.ingestion_runs add column if not exists records_failed integer not null default 0;
alter table public.ingestion_runs add column if not exists records_published integer not null default 0;
alter table public.ingestion_runs add column if not exists error_message text;
alter table public.ingestion_runs add column if not exists metadata jsonb not null default '{}'::jsonb;
-- Old audit rows did not have the current provenance contract. Retain their
-- original status in private metadata, but never let them authorize publication.
do $$ declare item record; begin
  for item in select conname from pg_constraint where conrelid='public.ingestion_runs'::regclass
    and contype='c' and pg_get_constraintdef(oid) ilike '%status%' loop
    execute format('alter table public.ingestion_runs drop constraint %I',item.conname);
  end loop;
end $$;
update public.ingestion_runs set run_key='legacy-'||id::text,
  metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('legacy_status',status,'audit_gap',true),
  status='partial', finished_at=now(), heartbeat_at=now()
  where run_key is null or run_key='';
alter table public.ingestion_runs alter column run_key set not null;
alter table public.ingestion_runs alter column county_id set not null;
alter table public.ingestion_runs add constraint ingestion_runs_status_v2
  check (status in ('running','completed','partial','failed','skipped'));
alter table public.ingestion_runs add constraint ingestion_runs_terminal_v2
  check ((status='running')=(finished_at is null));
create unique index if not exists idx_ingestion_runs_run_key on public.ingestion_runs(run_key);
create unique index if not exists idx_ingestion_runs_id_county on public.ingestion_runs(id,county_id);

alter table public.properties alter column has_improvements drop not null;
alter table public.properties alter column has_improvements drop default;
alter table public.properties alter column tax_delinquent_years drop not null;
alter table public.properties alter column tax_delinquent_years drop default;
alter table public.properties add column if not exists source_url text;
alter table public.properties add column if not exists source_record_id text;
alter table public.properties add column if not exists source_fingerprint text;
alter table public.properties add column if not exists source_payload_hash text;
alter table public.properties add column if not exists vacancy_status text not null default 'unknown';
alter table public.properties add column if not exists vacancy_evidence jsonb not null default '{}'::jsonb;
alter table public.properties add column if not exists last_seen_at timestamptz;
create unique index if not exists idx_properties_id_county on public.properties(id, county_id);
-- Fail visibly if a preexisting deployment has duplicates; do not delete history.
create unique index if not exists idx_deals_one_per_property on public.deals(property_id);

create table if not exists public.ingestion_records (
  id bigint generated by default as identity primary key,
  run_id bigint not null,
  county_id text not null,
  record_key text not null,
  source_record_id text,
  source_url text,
  raw_payload jsonb not null default '{}'::jsonb,
  normalized_payload jsonb not null default '{}'::jsonb,
  field_mapping jsonb not null default '{}'::jsonb,
  property_id bigint,
  deal_id bigint references public.deals(id) on delete set null,
  status text not null,
  rejection_reason text,
  hold_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key(run_id, county_id) references public.ingestion_runs(id, county_id),
  foreign key(property_id, county_id) references public.properties(id, county_id),
  unique(run_id, record_key)
);

alter table public.ingestion_records add column if not exists run_id bigint;
alter table public.ingestion_records add column if not exists county_id text;
alter table public.ingestion_records add column if not exists record_key text;
alter table public.ingestion_records add column if not exists source_record_id text;
alter table public.ingestion_records add column if not exists source_url text;
alter table public.ingestion_records add column if not exists raw_payload jsonb not null default '{}'::jsonb;
alter table public.ingestion_records add column if not exists normalized_payload jsonb not null default '{}'::jsonb;
alter table public.ingestion_records add column if not exists field_mapping jsonb not null default '{}'::jsonb;
alter table public.ingestion_records add column if not exists property_id bigint;
alter table public.ingestion_records add column if not exists deal_id bigint;
alter table public.ingestion_records add column if not exists status text not null default 'normalized';
alter table public.ingestion_records add column if not exists rejection_reason text;
alter table public.ingestion_records add column if not exists hold_reason text;
alter table public.ingestion_records add column if not exists created_at timestamptz not null default now();
alter table public.ingestion_records add column if not exists updated_at timestamptz not null default now();
update public.ingestion_records set record_key='legacy-'||id::text where record_key is null;
alter table public.ingestion_records alter column run_id set not null;
alter table public.ingestion_records alter column county_id set not null;
alter table public.ingestion_records alter column record_key set not null;
create unique index if not exists idx_ingestion_records_run_key on public.ingestion_records(run_id,record_key);
-- Named scoped constraints also protect upgraded legacy tables.
alter table public.ingestion_records add constraint ingestion_records_run_scope_v2
  foreign key(run_id,county_id) references public.ingestion_runs(id,county_id);
alter table public.ingestion_records add constraint ingestion_records_property_scope_v2
  foreign key(property_id,county_id) references public.properties(id,county_id);
alter table public.ingestion_records add constraint ingestion_records_deal_v2
  foreign key(deal_id) references public.deals(id) on delete set null;
alter table public.ingestion_runs add constraint ingestion_runs_county_v2
  foreign key(county_id) references public.counties(county_id);
create index if not exists idx_ingestion_records_property on public.ingestion_records(property_id);
create index if not exists idx_ingestion_runs_county_started on public.ingestion_runs(county_id, started_at desc);
create index if not exists idx_ingestion_runs_stale on public.ingestion_runs(heartbeat_at) where status='running';
drop trigger if exists ingestion_records_set_updated_at on public.ingestion_records;
create trigger ingestion_records_set_updated_at before update on public.ingestion_records
  for each row execute function public.set_updated_at();

alter table public.deals add column if not exists asking_price_basis text;
alter table public.deals add column if not exists financial_evidence jsonb not null default '{}'::jsonb;
alter table public.deals add column if not exists ingestion_record_id bigint references public.ingestion_records(id);
alter table public.deals add column if not exists verified_at timestamptz;
alter table public.deals add column if not exists verification_expires_at timestamptz;
alter table public.deals add column if not exists revision bigint not null default 0;
alter table public.deals alter column deal_score drop not null;
alter table public.deals alter column deal_score drop default;
alter table public.deals add column if not exists valuation_model text;
alter table public.deals alter column verification_status set default 'pending_review';

alter table public.comps add column if not exists source_url text;
alter table public.comps add column if not exists source_record_id text;
alter table public.comps add column if not exists source_apn text;
alter table public.comps add column if not exists county_id text references public.counties(county_id);
alter table public.comps add column if not exists sale_qualified boolean;
alter table public.comps add column if not exists vacant_at_sale boolean;
alter table public.comps add column if not exists ingestion_record_id bigint references public.ingestion_records(id);
create unique index if not exists idx_comps_identity on public.comps(deal_id, source_url, source_record_id);

alter table public.ingestion_runs enable row level security;
alter table public.ingestion_records enable row level security;
revoke all on public.ingestion_runs, public.ingestion_records from public, anon, authenticated;
grant all on public.counties, public.properties, public.deals, public.comps,
  public.ingestion_runs, public.ingestion_records, public.waitlist, public.subscribers, public.deliveries to service_role;
grant usage, select on all sequences in schema public to service_role;
grant select (asking_price_basis, verified_at, verification_expires_at, valuation_model) on public.deals to anon, authenticated;
grant select (source_url, source_record_id, source_apn, county_id, sale_qualified, vacant_at_sale)
  on public.comps to anon, authenticated;

create or replace function public.finite_number(value numeric)
returns boolean language sql immutable set search_path=public as $$
  select value is not null and value::text not in ('NaN','Infinity','-Infinity');
$$;

-- Replace comparables in one transaction; DELETE+POST over REST is not atomic.
create or replace function public.replace_deal_comps(p_deal_id bigint, p_comps jsonb)
returns integer language plpgsql security invoker set search_path = public as $$
declare inserted integer;
begin
  if p_comps is null or jsonb_typeof(p_comps) is distinct from 'array' or jsonb_array_length(p_comps) > 100 then
    raise exception 'Invalid comparable collection';
  end if;
  perform 1 from public.deals where id=p_deal_id for update;
  if not found then raise exception 'Deal not found'; end if;
  if exists (select 1 from jsonb_array_elements(p_comps) c where
      nullif(c->>'source_url','') is null or nullif(c->>'source_record_id','') is null
      or not public.finite_number((c->>'sale_price')::numeric) or (c->>'sale_price')::numeric <= 0
      or not public.finite_number((c->>'lot_size_acres')::numeric) or (c->>'lot_size_acres')::numeric <= 0
      or not public.finite_number((c->>'distance_miles')::numeric) or (c->>'distance_miles')::numeric < 0
      or nullif(c->>'sale_date','') is null) then
    raise exception 'Invalid comparable evidence';
  end if;
  update public.deals set verification_status='pending_review', verified_at=null where id=p_deal_id;
  delete from public.comps where deal_id=p_deal_id;
  insert into public.comps(deal_id,address,sale_price,sale_date,distance_miles,lot_size_acres,price_per_acre,
    source_url,source_record_id,source_apn,county_id,sale_qualified,vacant_at_sale,ingestion_record_id)
  select p_deal_id,c.address,c.sale_price,c.sale_date,c.distance_miles,c.lot_size_acres,c.sale_price/c.lot_size_acres,
    c.source_url,c.source_record_id,c.source_apn,c.county_id,c.sale_qualified,c.vacant_at_sale,c.ingestion_record_id
  from jsonb_to_recordset(p_comps) as c(address text,sale_price numeric,sale_date timestamptz,distance_miles numeric,
    lot_size_acres numeric,price_per_acre numeric,source_url text,source_record_id text,source_apn text,
    county_id text,sale_qualified boolean,vacant_at_sale boolean,ingestion_record_id bigint);
  get diagnostics inserted = row_count;
  return inserted;
end;
$$;
revoke all on function public.replace_deal_comps(bigint,jsonb) from public, anon, authenticated;
grant execute on function public.replace_deal_comps(bigint,jsonb) to service_role;


create or replace function public.hold_deals_for_parcels(p_county_id text, p_apns text[])
returns integer language plpgsql security invoker set search_path=public as $$
declare changed integer;
begin
  if coalesce(array_length(p_apns,1),0)>250 then raise exception 'Parcel batch exceeds limit'; end if;
  update public.deals d set verification_status='pending_review',verified_at=null,verification_expires_at=null
    from public.properties p where p.id=d.property_id and p.county_id=p_county_id and p.apn=any(p_apns);
  get diagnostics changed=row_count;
  return changed;
end;
$$;
revoke all on function public.hold_deals_for_parcels(text,text[]) from public, anon, authenticated;
grant execute on function public.hold_deals_for_parcels(text,text[]) to service_role;
