import { cookies } from 'next/headers'
import { createServerClient } from '@supabase/ssr'
import SignOutButton from './SignOutButton'
import Workspace from './Workspace'

export default async function MyDealScanPage() {
  const cookieStore = await cookies()
  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!, { cookies: { getAll: () => cookieStore.getAll(), setAll: () => {} } })
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return <main className="grid min-h-screen place-items-center bg-[#f7f9f7] px-4 py-16"><div className="w-full max-w-lg rounded-[2rem] border border-[#dfe7e2] bg-white p-8 text-center shadow-[0_18px_60px_rgba(23,42,32,.06)]"><span className="rounded-full bg-[#e8f4ec] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.14em] text-[#176b45]">My DealScan</span><h1 className="mt-5 text-3xl font-black tracking-[-.04em] text-[#153025]">Your research workspace.</h1><p className="mt-3 text-sm leading-6 text-[#69766f]">Sign in to keep a shortlist, review your research trail and compare opportunities.</p><a href="/auth" className="mt-7 inline-flex rounded-xl bg-[#153025] px-5 py-3 text-sm font-bold text-white hover:bg-[#176b45]">Sign in →</a><a href="/deals" className="ml-2 mt-7 inline-flex rounded-xl border border-[#dfe7e2] px-5 py-3 text-sm font-bold text-[#34423b]">Explore first</a></div></main>
  return <main className="min-h-screen bg-[#f7f9f7] text-[#15211b]"><header className="sticky top-0 z-30 border-b border-[#e4ebe7] bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><a href="/" className="text-[17px] font-black">Deal<span className="text-[#176b45]">Scan</span></a><nav className="hidden items-center gap-1 md:flex"><a href="/deals" className="rounded-xl px-3 py-2 text-sm font-bold text-[#65726b] hover:bg-[#f4f7f5]">Explore</a><a href="/compare" className="rounded-xl px-3 py-2 text-sm font-bold text-[#65726b] hover:bg-[#f4f7f5]">Compare</a><a href="/my-dealscan" className="rounded-xl bg-[#edf5f0] px-3 py-2 text-sm font-bold text-[#176b45]">My DealScan</a></nav><div className="flex items-center gap-3"><span className="hidden max-w-[240px] truncate text-xs text-[#69766f] sm:block">{user.email}</span><SignOutButton /></div></div></header><section className="mx-auto max-w-7xl px-4 pt-10 pb-24 sm:px-6 sm:pt-14"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#176b45]">Personal workspace</p><h1 className="mt-2 text-4xl font-black tracking-[-.045em]">Research without losing your place.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#68756e]">Save promising parcels, build a verification queue and compare candidates before you move from screening to action.</p><Workspace /></section><nav className="fixed inset-x-0 bottom-0 z-40 border-t border-[#dfe7e2] bg-white/95 px-4 py-2 backdrop-blur md:hidden"><div className="mx-auto grid max-w-lg grid-cols-3 gap-1"><a href="/deals" className="rounded-xl p-2 text-center text-[10px] font-bold text-[#718078]">Explore</a><a href="/my-dealscan" className="rounded-xl bg-[#edf5f0] p-2 text-center text-[10px] font-black text-[#176b45]">Saved</a><a href="/compare" className="rounded-xl p-2 text-center text-[10px] font-bold text-[#718078]">Compare</a></div></nav></main>
}
