"""
DealScan - Expansion batch definition.

The first expansion batch targets high-value counties in Arizona, Texas,
New Mexico, Colorado, Nevada, Utah, Oklahoma, Arkansas, Missouri,
Tennessee, Georgia, Florida, North Carolina, South Carolina,
Mississippi, Alabama, Kentucky, Kansas, Nebraska, Montana, Wyoming,
Idaho, Oregon, Washington, California.

Only counties with likely public ArcGIS parcel data are included.
This is a seed list for source discovery; actual adapters must be
verified by `python main.py --probe-all`.
"""
from __future__ import annotations

from typing import Any, Dict

BATCH_STATES = [
    "Arizona",
    "Texas",
    "New Mexico",
    "Colorado",
    "Nevada",
    "Utah",
    "Oklahoma",
    "Arkansas",
    "Missouri",
    "Tennessee",
    "Georgia",
    "Florida",
    "North Carolina",
    "South Carolina",
    "Mississippi",
    "Alabama",
    "Kentucky",
    "Kansas",
    "Nebraska",
    "Montana",
    "Wyoming",
    "Idaho",
    "Oregon",
    "Washington",
    "California",
]

# Candidate counties for the first expansion batch.
# These are research-informed candidates; they MUST be probed and verified
# before being marked production-ready.
EXPANSION_BATCH: Dict[str, Dict[str, Any]] = {
    # Arizona
    "pima_az": {
        "county_name": "Pima County",
        "state": "Arizona",
        "state_fips": "04",
        "county_fips": "019",
        "geoid": "04019",
        "population": 1_055_000,
        "assessor_url": "https://www.pima.gov/259/Assessor-Recorder",
        "notes": "Tucson metro; strong investor demand.",
    },
    "maricopa_az": {
        "county_name": "Maricopa County",
        "state": "Arizona",
        "state_fips": "04",
        "county_fips": "013",
        "geoid": "04013",
        "population": 4_585_000,
        "assessor_url": "https://www.mcassessor.maricopa.gov",
        "notes": "Phoenix metro; highest volume AZ county.",
    },
    # New Mexico
    "dona_ana_nm": {
        "county_name": "Doña Ana County",
        "state": "New Mexico",
        "state_fips": "35",
        "county_fips": "029",
        "geoid": "35029",
        "population": 219_000,
        "assessor_url": "https://www.donaanacounty.org/departments/assessor",
        "notes": "Las Cruces; border county with active land market.",
    },
    "bern_nalo_nm": {
        "county_name": "Bernalillo County",
        "state": "New Mexico",
        "state_fips": "35",
        "county_fips": "001",
        "geoid": "35001",
        "population": 677_000,
        "assessor_url": "https://www.bernco.gov/assessor",
        "notes": "Albuquerque metro; large parcel inventory.",
    },
    # Texas
    "bexar_tx": {
        "county_name": "Bexar County",
        "state": "Texas",
        "state_fips": "48",
        "county_fips": "029",
        "geoid": "48029",
        "population": 2_005_000,
        "assessor_url": "https://www.bcad.org",
        "notes": "San Antonio metro; large CAD with ArcGIS history.",
    },
    "travis_tx": {
        "county_name": "Travis County",
        "state": "Texas",
        "state_fips": "48",
        "county_fips": "453",
        "geoid": "48453",
        "population": 1_295_000,
        "assessor_url": "https://www.traviscad.org",
        "notes": "Austin metro; high land values.",
    },
    "hidalgo_tx": {
        "county_name": "Hidalgo County",
        "state": "Texas",
        "state_fips": "48",
        "county_fips": "215",
        "geoid": "48215",
        "population": 881_000,
        "assessor_url": "https://www.hcad.org",
        "notes": "Rio Grande Valley; active rural land market.",
    },
    # Colorado
    "boulder_co": {
        "county_name": "Boulder County",
        "state": "Colorado",
        "state_fips": "08",
        "county_fips": "013",
        "geoid": "08013",
        "population": 326_000,
        "assessor_url": "https://www.bouldercounty.org/assessor",
        "notes": "Mountain land; strong open-data presence.",
    },
    "el_paso_co": {
        "county_name": "El Paso County",
        "state": "Colorado",
        "state_fips": "08",
        "county_fips": "041",
        "geoid": "08041",
        "population": 730_000,
        "assessor_url": "https://www.elpasoco.com/assessor",
        "notes": "Colorado Springs metro.",
    },
    # Nevada
    "clark_nv": {
        "county_name": "Clark County",
        "state": "Nevada",
        "state_fips": "32",
        "county_fips": "003",
        "geoid": "32003",
        "population": 2_292_000,
        "assessor_url": "https://www.clarkcountynv.gov/assessor",
        "notes": "Las Vegas metro; high desert land parcels.",
    },
    "washoe_nv": {
        "county_name": "Washoe County",
        "state": "Nevada",
        "state_fips": "32",
        "county_fips": "031",
        "geoid": "32031",
        "population": 486_000,
        "assessor_url": "https://www.washoecounty.gov/assessor",
        "notes": "Reno metro; growing parcel volume.",
    },
    # Utah
    "salt_lake_ut": {
        "county_name": "Salt Lake County",
        "state": "Utah",
        "state_fips": "49",
        "county_fips": "035",
        "geoid": "49035",
        "population": 1_185_000,
        "assessor_url": "https://slco.org/assessor",
        "notes": "Salt Lake City metro; high parcel counts.",
    },
    "utah_ut": {
        "county_name": "Utah County",
        "state": "Utah",
        "state_fips": "49",
        "county_fips": "049",
        "geoid": "49049",
        "population": 659_000,
        "assessor_url": "https://www.utahcounty.gov/Assessor",
        "notes": "Provo/Orem; strong residential land market.",
    },
    # Oklahoma
    "oklahoma_ok": {
        "county_name": "Oklahoma County",
        "state": "Oklahoma",
        "state_fips": "40",
        "county_fips": "109",
        "geoid": "40109",
        "population": 807_000,
        "assessor_url": "https://www.oklahomacounty.org/assessor",
        "notes": "Oklahoma City metro.",
    },
    "tulsa_ok": {
        "county_name": "Tulsa County",
        "state": "Oklahoma",
        "state_fips": "40",
        "county_fips": "143",
        "geoid": "40143",
        "population": 651_000,
        "assessor_url": "https://www.tulsacounty.org/assessor",
        "notes": "Tulsa metro; active land deals.",
    },
    # Arkansas
    "pulaski_ar": {
        "county_name": "Pulaski County",
        "state": "Arkansas",
        "state_fips": "05",
        "county_fips": "119",
        "geoid": "05119",
        "population": 399_000,
        "assessor_url": "https://www.pulaskicountyassessor.com",
        "notes": "Little Rock metro.",
    },
    # Missouri
    "st_louis_mo": {
        "county_name": "St. Louis County",
        "state": "Missouri",
        "state_fips": "29",
        "county_fips": "189",
        "geoid": "29189",
        "population": 996_000,
        "assessor_url": "https://stlouiscountymo.gov/assessor",
        "notes": "St. Louis metro; large suburban land base.",
    },
    "jackson_mo": {
        "county_name": "Jackson County",
        "state": "Missouri",
        "state_fips": "29",
        "county_fips": "095",
        "geoid": "29095",
        "population": 703_000,
        "assessor_url": "https://www.jacksongov.org/assessor",
        "notes": "Kansas City metro.",
    },
    # Tennessee
    "shelby_tn": {
        "county_name": "Shelby County",
        "state": "Tennessee",
        "state_fips": "47",
        "county_fips": "157",
        "geoid": "47157",
        "population": 935_000,
        "assessor_url": "https://www.shelbycountytn.gov/Assessor",
        "notes": "Memphis metro.",
    },
    "davidson_tn": {
        "county_name": "Davidson County",
        "state": "Tennessee",
        "state_fips": "47",
        "county_fips": "037",
        "geoid": "47037",
        "population": 715_000,
        "assessor_url": "https://www.nashville.gov/Assessor-of-Property",
        "notes": "Nashville metro; high demand.",
    },
    # Georgia
    "fulton_ga": {
        "county_name": "Fulton County",
        "state": "Georgia",
        "state_fips": "13",
        "county_fips": "121",
        "geoid": "13121",
        "population": 1_079_000,
        "assessor_url": "https://www.fultonassessor.org",
        "notes": "Atlanta metro; largest GA county.",
    },
    "cobb_ga": {
        "county_name": "Cobb County",
        "state": "Georgia",
        "state_fips": "13",
        "county_fips": "067",
        "geoid": "13067",
        "population": 766_000,
        "assessor_url": "https://www.cobbcounty.org/assessor",
        "notes": "Atlanta suburbs.",
    },
    # Florida
    "hillsborough_fl": {
        "county_name": "Hillsborough County",
        "state": "Florida",
        "state_fips": "12",
        "county_fips": "057",
        "geoid": "12057",
        "population": 1_512_000,
        "assessor_url": "https://www.hcpafl.org",
        "notes": "Tampa metro.",
    },
    "orange_fl": {
        "county_name": "Orange County",
        "state": "Florida",
        "state_fips": "12",
        "county_fips": "095",
        "geoid": "12095",
        "population": 1_392_000,
        "assessor_url": "https://www.occompt.com",
        "notes": "Orlando metro.",
    },
    # North Carolina
    "mecklenburg_nc": {
        "county_name": "Mecklenburg County",
        "state": "North Carolina",
        "state_fips": "37",
        "county_fips": "119",
        "geoid": "37119",
        "population": 1_122_000,
        "assessor_url": "https://www.mecknc.gov/assessor",
        "notes": "Charlotte metro.",
    },
    "wake_nc": {
        "county_name": "Wake County",
        "state": "North Carolina",
        "state_fips": "37",
        "county_fips": "183",
        "geoid": "37183",
        "population": 1_128_000,
        "assessor_url": "https://www.wake.gov/assessor",
        "notes": "Raleigh metro.",
    },
    # South Carolina
    "greenville_sc": {
        "county_name": "Greenville County",
        "state": "South Carolina",
        "state_fips": "45",
        "county_fips": "045",
        "geoid": "45045",
        "population": 523_000,
        "assessor_url": "https://www.greenvillecounty.org/assessor",
        "notes": "Upstate SC; manufacturing and residential land.",
    },
    # Mississippi
    "hinds_ms": {
        "county_name": "Hinds County",
        "state": "Mississippi",
        "state_fips": "28",
        "county_fips": "049",
        "geoid": "28049",
        "population": 227_000,
        "assessor_url": "https://www.hindscountyms.gov/assessor",
        "notes": "Jackson metro; rural land opportunities.",
    },
    # Alabama
    "jefferson_al": {
        "county_name": "Jefferson County",
        "state": "Alabama",
        "state_fips": "01",
        "county_fips": "073",
        "geoid": "01073",
        "population": 662_000,
        "assessor_url": "https://www.jeffconline.org/assessor",
        "notes": "Birmingham metro.",
    },
    "mobile_al": {
        "county_name": "Mobile County",
        "state": "Alabama",
        "state_fips": "01",
        "county_fips": "097",
        "geoid": "01097",
        "population": 413_000,
        "assessor_url": "https://www.mobilecountyal.gov/assessor",
        "notes": "Coastal AL; land near waterways.",
    },
    # Kentucky
    "jefferson_ky": {
        "county_name": "Jefferson County",
        "state": "Kentucky",
        "state_fips": "21",
        "county_fips": "111",
        "geoid": "21111",
        "population": 782_000,
        "assessor_url": "https://louisvilleky.gov/government/property-taxes",
        "notes": "Louisville metro.",
    },
    # Kansas
    "sedgwick_ks": {
        "county_name": "Sedgwick County",
        "state": "Kansas",
        "state_fips": "20",
        "county_fips": "173",
        "geoid": "20173",
        "population": 511_000,
        "assessor_url": "https://www.sedgwickcounty.org/assessor",
        "notes": "Wichita metro.",
    },
    # Nebraska
    "lancaster_ne": {
        "county_name": "Lancaster County",
        "state": "Nebraska",
        "state_fips": "31",
        "county_fips": "109",
        "geoid": "31109",
        "population": 322_000,
        "assessor_url": "https://lancastercounty.ne.gov/assessor",
        "notes": "Lincoln metro.",
    },
    # Montana
    "yellowstone_mt": {
        "county_name": "Yellowstone County",
        "state": "Montana",
        "state_fips": "30",
        "county_fips": "111",
        "geoid": "30111",
        "population": 164_000,
        "assessor_url": "https://www.yellowstonecounty-mt.gov/assessor",
        "notes": "Billings metro; large rural land base.",
    },
    # Wyoming
    "laramie_wy": {
        "county_name": "Laramie County",
        "state": "Wyoming",
        "state_fips": "56",
        "county_fips": "021",
        "geoid": "56021",
        "population": 100_000,
        "assessor_url": "https://www.laramiecounty.com/assessor",
        "notes": "Cheyenne metro; eastern plains land.",
    },
    # Idaho
    "ada_id": {
        "county_name": "Ada County",
        "state": "Idaho",
        "state_fips": "16",
        "county_fips": "001",
        "geoid": "16001",
        "population": 495_000,
        "assessor_url": "https://www.adacounty.id.gov/assessor",
        "notes": "Boise metro; fast-growing land market.",
    },
    # Oregon
    "multnomah_or": {
        "county_name": "Multnomah County",
        "state": "Oregon",
        "state_fips": "41",
        "county_fips": "051",
        "geoid": "41051",
        "population": 812_000,
        "assessor_url": "https://www.multco.us/assessor",
        "notes": "Portland metro; high land values.",
    },
    # Washington
    "king_wa": {
        "county_name": "King County",
        "state": "Washington",
        "state_fips": "53",
        "county_fips": "033",
        "geoid": "53033",
        "population": 2_269_000,
        "assessor_url": "https://www.kingcounty.gov/assessor",
        "notes": "Seattle metro; largest WA county.",
    },
    "pierce_wa": {
        "county_name": "Pierce County",
        "state": "Washington",
        "state_fips": "53",
        "county_fips": "053",
        "geoid": "53053",
        "population": 928_000,
        "assessor_url": "https://www.co.pierce.wa.us/assessor",
        "notes": "Tacoma metro; Puget Sound land.",
    },
    # California
    "riverside_ca": {
        "county_name": "Riverside County",
        "state": "California",
        "state_fips": "06",
        "county_fips": "065",
        "geoid": "06065",
        "population": 2_470_000,
        "assessor_url": "https://www.assessor-riverside.org",
        "notes": "Inland Empire; large desert/rural land base.",
    },
    "sacramento_ca": {
        "county_name": "Sacramento County",
        "state": "California",
        "state_fips": "06",
        "county_fips": "067",
        "geoid": "06067",
        "population": 1_550_000,
        "assessor_url": "https://assessor.saccounty.gov",
        "notes": "Sacramento metro; Central Valley land.",
    },
    "san_bernardino_ca": {
        "county_name": "San Bernardino County",
        "state": "California",
        "state_fips": "06",
        "county_fips": "071",
        "geoid": "06071",
        "population": 2_209_000,
        "assessor_url": "https://www.sbcounty.gov/assessor",
        "notes": "Largest US county by area; high desert land.",
    },
}
